# Configuration for Carrier Phase Synchronization Simulation
# This simulates the Nanzer paper approach with MPS localization

simulation:
  name: "Carrier Phase Sync + Decentralized MPS"
  description: "Simulates S-band carrier phase synchronization with millimeter-level ranging"
  num_trials: 10
  random_seed: 42

network:
  n_sensors: 20
  n_anchors: 4
  scale_meters: 10.0
  communication_range_factor: 0.5  # As fraction of network scale
  
  # Anchor placement strategy
  anchor_placement: "corners"  # Options: corners, random, optimal
  
carrier_phase:
  frequency_ghz: 2.4  # S-band
  phase_noise_milliradians: 1.0  # Achievable with RF hardware
  frequency_stability_ppb: 0.1  # With OCXO
  coarse_time_accuracy_ns: 1.0  # For ambiguity resolution

mps_algorithm:
  max_iterations: 500
  convergence_tolerance: 1e-5
  use_sdp_init: true
  use_anderson_acceleration: true
  anderson_memory: 5
  use_adaptive_steps: true
  
visualization:
  show_plots: true
  save_plots: true
  output_dir: "visualizations/"
  figure_format: "png"
  dpi: 150
  style: "publication"  # Options: publication, presentation, default

performance_requirements:
  sband_rmse_mm: 15.0  # S-band coherent beamforming requirement
  
output:
  save_results: true
  results_file: "results/phase_sync_results.json"
  verbose: true