# Quick Test Configuration
# For rapid algorithm testing and debugging
# Runs in <5 seconds on most machines

network:
  n_sensors: 10           # Small network
  n_anchors: 4            # Minimum anchors
  communication_range: 0.5 # Dense connectivity for reliable convergence
  dimension: 2

measurements:
  noise_factor: 0.02      # Low noise for validation
  seed: 123               # Fixed seed for reproducibility

algorithm:
  name: "mps"
  gamma: 0.95             # Lower gamma for faster convergence
  alpha: 1.5              # Aggressive step size
  max_iterations: 100     # Quick execution
  tolerance: 0.001        # Relaxed tolerance for speed

output:
  save_results: true
  output_dir: "results/quick_test/"
  verbose: true           # See what's happening
  save_interval: 0        # Don't save intermediate