# Research Comparison Configuration
# For comparing MPS vs ADMM algorithms
# Produces publication-quality results

network:
  n_sensors: 30           # Standard research size
  n_anchors: 6            # 20% anchors
  communication_range: 0.3 # Typical connectivity
  dimension: 2
  scale: 10.0             # 10m x 10m area

measurements:
  noise_factor: 0.05      # 5% noise (realistic)
  seed: 42                # Reproducible
  measurement_type: "distance"

algorithm:
  # Will be overridden when running comparison
  name: "both"            # Compare both algorithms
  
  # MPS parameters
  gamma: 0.99
  alpha: 1.0
  
  # ADMM parameters  
  rho: 1.0
  admm_alpha: 1.5
  
  # Convergence
  max_iterations: 500
  tolerance: 0.00001      # High precision
  patience: 50

output:
  save_results: true
  output_dir: "results/comparison_{date}/"
  format: "json"
  verbose: false          # Quiet for batch runs
  save_interval: 50
  save_history: true      # Important for comparison
  save_plots: true
  plot_format: "pdf"      # Publication quality
  plot_dpi: 300

validation:
  compute_crlb: true      # Compare to theoretical bound
  compare_truth: true
  confidence_intervals: true
  confidence_level: 0.95
  metrics:
    - "rmse"
    - "mae"
    - "convergence_rate"
    - "efficiency"

visualization:
  show_plots: false       # Batch processing
  style: "paper"          # Publication style
  colors: "colorblind"    # Accessible colors