# Configuration for large network testing
# Stress test with many sensors and distributed execution

network:
  n_sensors: 100         # Large network
  n_anchors: 10          # More anchors for better coverage
  communication_range: 0.2  # Smaller range (sparser network)
  dimension: 2

measurements:
  noise_factor: 0.08     # Higher noise for realistic scenario
  seed: 999

algorithm:
  gamma: 0.999           # High gamma for stability
  alpha: 0.8             # Smaller step size for stability
  max_iterations: 1000   # More iterations for convergence
  tolerance: 0.000001    # Tighter tolerance

mpi:
  enable: true           # Use MPI for large network
  n_processes: 8         # More processes for parallelization

output:
  save_results: true
  output_dir: "results/large/"
  verbose: false         # Less verbose for large network
  save_interval: 100     # Save less frequently