# Default configuration for MPS algorithm
# Matrix-Parametrized Proximal Splitting for Sensor Network Localization

network:
  n_sensors: 30          # Number of sensors to localize
  n_anchors: 6           # Number of anchors (known positions)
  communication_range: 0.3  # Maximum communication distance
  dimension: 2           # 2D or 3D localization

measurements:
  noise_factor: 0.05     # Noise level in distance measurements (0.05 = 5%)
  seed: 42               # Random seed for reproducibility

algorithm:
  gamma: 0.99            # Consensus mixing parameter (0 < gamma < 1)
  alpha: 1.0             # Proximal step size parameter
  max_iterations: 500    # Maximum number of iterations
  tolerance: 0.00001     # Convergence tolerance

mpi:
  enable: false          # Enable MPI distributed execution
  n_processes: 4         # Number of MPI processes (if enabled)

output:
  save_results: true     # Save results to file
  output_dir: "results/" # Output directory
  verbose: true          # Verbose logging
  save_interval: 50      # Save intermediate results every N iterations