# Quick Test Configuration
# Minimal setup for rapid testing and verification

network:
  n_sensors: 10
  n_anchors: 3
  scale: 10.0
  dimension: 2
  communication_range: 0.5

measurements:
  measurement_type: "distance"
  noise_factor: 0.01
  seed: 42

algorithm:
  name: "mps"
  gamma: 0.99
  alpha: 1.0
  max_iterations: 100
  tolerance: 1e-4

output:
  save_results: true
  output_dir: "results/"
  verbose: false