# S-Band Precision Localization Configuration
# Achieves millimeter-level accuracy using carrier phase synchronization
# Based on Nanzer 2017 paper: "Precise millimeter-wave time transfer"

# ============================================================================
# CARRIER PHASE SYNCHRONIZATION (S-BAND)
# ============================================================================
carrier_phase:
  # S-band carrier frequency (2.4 GHz standard)
  frequency_ghz: 2.4
  
  # Wavelength at 2.4 GHz = 12.5 cm
  # Phase resolution = λ/(2π) ≈ 2 mm per radian
  
  # Phase measurement accuracy (achievable with RF hardware)
  phase_noise_milliradians: 1.0  # 1 mrad = 2mm ranging error
  
  # Frequency stability with OCXO (Oven-Controlled Crystal Oscillator)
  frequency_stability_ppb: 0.1  # 0.1 parts per billion
  
  # Coarse time sync for ambiguity resolution
  # Only needs to be better than λ/2 = 6.25 cm
  coarse_time_accuracy_ns: 1.0  # 1 ns = 30 cm (sufficient)

# ============================================================================
# TIME SYNCHRONIZATION
# ============================================================================
time_sync:
  # Two-Way Time Transfer (TWTT) for coarse synchronization
  enable: true
  protocol: "twtt"
  
  # Initial offset before sync (typical for unsynchronized nodes)
  initial_offset_ns: 1000  # 1 microsecond initial offset
  
  # Target accuracy after TWTT
  target_accuracy_ns: 1.0  # 1 ns (30 cm) for ambiguity resolution
  
  # Number of TWTT exchanges
  num_exchanges: 10
  
  # Clock drift compensation
  drift_ppm: 1.0  # 1 ppm drift rate (typical for OCXO)

# ============================================================================
# FREQUENCY SYNCHRONIZATION
# ============================================================================
frequency_sync:
  # Enable frequency tracking
  enable: true
  
  # Tracking duration for frequency estimation
  observation_time_seconds: 1.0
  
  # Frequency estimation accuracy target
  target_accuracy_ppb: 0.1  # Match OCXO stability
  
  # Update rate for frequency corrections
  update_interval_ms: 100

# ============================================================================
# NETWORK CONFIGURATION
# ============================================================================
network:
  # Moderate size network for demonstration
  n_sensors: 30
  n_anchors: 6
  
  # Physical dimensions
  scale: 50.0  # 50m x 50m area (typical for coherent beamforming)
  dimension: 2  # 2D localization
  
  # Communication range (fraction of network diameter)
  communication_range: 0.3  # Ensures connectivity
  
  # Topology for optimal anchor placement
  topology: "grid"
  anchor_placement: "corners_and_center"  # Optimal for 2D

# ============================================================================
# MPS ALGORITHM (WITH CARRIER PHASE)
# ============================================================================
algorithm:
  name: "mps"
  
  # Use tighter parameters for high precision
  gamma: 0.999  # Very stable convergence
  alpha: 0.5     # Conservative step size for precision
  
  # Convergence settings for mm accuracy
  max_iterations: 1000
  tolerance: 0.000001  # 1 micrometer convergence
  
  # Advanced features for high precision
  use_sdp_init: true  # Semidefinite programming initialization
  use_anderson_acceleration: true  # Faster convergence
  anderson_memory: 5
  use_adaptive_steps: true

# ============================================================================
# MEASUREMENT MODEL
# ============================================================================
measurements:
  # Primary: Carrier phase measurements
  measurement_type: "carrier_phase"
  
  # Phase wrapping ambiguity resolution
  use_ambiguity_resolution: true
  
  # Combine coarse (time) and fine (phase) measurements
  fusion_method: "weighted"  # Weight by measurement accuracy
  
  # Measurement noise (millimeter level)
  phase_noise_mm: 2.0  # 2mm standard deviation
  
  # Outlier rejection for robustness
  outlier_rejection: true
  outlier_threshold_sigma: 3.0

# ============================================================================
# PERFORMANCE REQUIREMENTS (S-BAND)
# ============================================================================
requirements:
  # S-band coherent beamforming requirement
  max_rmse_mm: 15.0  # λ/8 at 2.4 GHz
  
  # Individual node accuracy
  max_node_error_mm: 20.0
  
  # Timing requirements
  max_sync_error_ns: 1.0  # For ambiguity resolution
  
  # Frequency stability
  max_frequency_error_ppb: 0.1

# ============================================================================
# SIMULATION SETTINGS
# ============================================================================
simulation:
  # Number of Monte Carlo trials
  num_trials: 10
  
  # Random seed for reproducibility
  random_seed: 42
  
  # Simulate realistic hardware constraints
  simulate_hardware: true
  
  # Hardware parameters
  adc_bits: 12  # 12-bit ADC typical
  sampling_rate_msps: 100  # 100 MS/s
  
  # RF front-end noise figure
  noise_figure_db: 3.0

# ============================================================================
# OUTPUT CONFIGURATION
# ============================================================================
output:
  save_results: true
  output_dir: "results/sband_precision/"
  
  # Detailed metrics to save
  metrics:
    - "rmse_mm"  # Root mean square error in millimeters
    - "cep_mm"   # Circular error probable (50% within)
    - "r95_mm"   # 95% radius
    - "max_error_mm"
    - "convergence_iterations"
    - "phase_ambiguities_resolved"
    - "sync_accuracy_achieved_ns"
    - "frequency_stability_achieved_ppb"
  
  # Visualization
  save_plots: true
  plot_convergence: true
  plot_error_distribution: true
  plot_phase_measurements: true

# ============================================================================
# EXPECTED RESULTS
# ============================================================================
# With this configuration, expect:
# - RMSE: 5-10 mm (meets S-band requirement of <15mm)
# - Maximum error: <20 mm
# - Time sync: <1 ns (sufficient for ambiguity resolution)
# - Frequency stability: 0.1 ppb (OCXO performance)
# - Convergence: 200-400 iterations
#
# Key insight: Carrier phase at 2.4 GHz provides 2mm resolution per radian
# Combined with coarse timing for ambiguity resolution = absolute mm accuracy