# Test configuration for millimeter accuracy with small network
# Designed to verify carrier phase synchronization works

carrier_phase:
  frequency_ghz: 2.4
  phase_noise_milliradians: 1.0  # 1 mrad = ~2mm error
  frequency_stability_ppb: 0.1
  coarse_time_accuracy_ns: 1.0

network:
  n_sensors: 10  # Small network for testing
  n_anchors: 4   # 4 corners
  scale: 10.0    # 10m x 10m area
  dimension: 2
  communication_range: 0.5  # Fully connected

algorithm:
  name: "mps"
  gamma: 0.999
  alpha: 0.5
  max_iterations: 500
  tolerance: 0.000001  # 1 micrometer

measurements:
  measurement_type: "carrier_phase"
  noise_factor: 0.001  # Very low noise
  seed: 42

output:
  save_results: true
  output_dir: "results/test_mm/"
  verbose: true