# Configuration for small network testing
# Good for quick tests and algorithm validation

network:
  n_sensors: 10          # Small network for testing
  n_anchors: 4           # Minimum anchors for 2D localization
  communication_range: 0.5  # Larger range for better connectivity
  dimension: 2

measurements:
  noise_factor: 0.02     # Low noise for validation
  seed: 123

algorithm:
  gamma: 0.95            # Slightly lower gamma for faster convergence
  alpha: 1.5             # Larger step size
  max_iterations: 200    # Fewer iterations needed
  tolerance: 0.0001      # Convergence tolerance

mpi:
  enable: false
  n_processes: 2

output:
  save_results: true
  output_dir: "results/small/"
  verbose: true
  save_interval: 20